apps/correo/urls.py
from django.conf.urls import patterns, url
from apps.correo.views import *




urlpatterns = patterns('apps.correo.views',
    # Examples:
    url(r'^/$', CorreoFormView.as_view(), name='indexCorreo'),
    #url(r'^/pdf/$', MyPDF.as_view(), name='pdf'),
    #url(r'^/graficos/$', Graficos.as_view(), name='graficos'),
    #url(r'^/grafico/(?P<numero>\d+)/$', GraficoDetalle.as_view(), name='graficoDetalle'),
    #url(r'^/graficos/primergraficopdf/$', 'PrimerInformePdf', name='primerGrafico'),
    #url(r'^/graficos/segundograficopdf/$', 'SegundoInformePdf', name='segundoGrafico'),
    #url(r'^encuesta/crear$', EncuestaCreateView.as_view(), name='crearEncuesta'),
    # url(r'^blog/', include('blog.urls')),


)

apps/encuesta/urls.py
from django.conf.urls import patterns, url
from apps.encuesta.views import *



urlpatterns = patterns('apps.encuesta.views',
    # Examples:
    url(r'^/$','encuesta_list', name='listaEncuesta'),
    url(r'^/export/(?P<encuesta_id>\d+)/$','exportPreguntasA', name='export'),   
    url(r'^/helpers/editaropcion/(?P<pk>\d+)/$', 'editarOpcion', name='editOpcion'),
    url(r'^/helpers/editarpregunta/(?P<pk>\d+)/$', 'editarPregunta', name='editPregunta'),
    url(r'^/helpers/eliminarpregunta/(?P<pregunta_id>\d+)/$', 'eliminarPregunta', name='eliminarPregunta'),
    url(r'^/helpers/eliminaropcion/(?P<opcion_id>\d+)/$', 'eliminarOpcion', name='eliminarOpcion'),
    url(r'^/crear$', EncuestaCreateView.as_view(), name='crearEncuesta'),
    #url(r'^encuesta/preguntas/(?P<encuesta_id>\d+)/$', 'crearPregunta', name='crearPreguntas'),
    url(r'^/preguntas/(?P<encuesta_id>\d+)/$', EncuestaPreguntaCreateView.as_view(), name='crearPreguntas'),
    url(r'^/ver/(?P<encuesta_id>\d+)/$', VisualizarEncuestaCreateView.as_view(), name='verEncuesta'),
    url(r'^/estadistica/(?P<encuesta_id>\d+)/$', EstadisticaView.as_view(), name='estadisticaEncuesta'),
    url(r'^/estadistica/(?P<encuesta_id>\d+)/pdf/$', EstadisticaViewPdf.as_view(), name='estadisticaPdfEncuesta'),
    #url(r'^/editar/(?P<encuesta_id>\d+)/$', EditarEncuestaView.as_view(), name='editarEncuesta'),
    #url(r'^/editar/(?P<encuesta_id>\d+)/$', EditarEncuestaPreguntaView.as_view(), name='editarPreguntaEncuesta'),
    url(r'^/suspender/(?P<encuesta_id>\d+)/$', 'suspenderEncuesta', name='suspenderEncuesta'),
    url(r'^/eliminar/(?P<encuesta_id>\d+)/$', 'eliminarEncuesta', name='eliminarEncuesta'),
    url(r'^/editar/(?P<encuesta_id>\d+)/$', EditarEncuestaPreguntaViewXeditable.as_view(), name='editarEncuesta'),
    url(r'^/editar/preguntas/(?P<encuesta_id>\d+)/(?P<pregunta_id>\d+)/$', EditarPreguntaView.as_view(), name='editarPregunta'),
    #url(r'^login$', 'iniciar_sesion', name='login'),
    #url(r'^', 'listaEgresados', name='listaEgresados'),
    #url(r'^egresado/addegresado/$', 'addEgresado', name='addEgresado'),
    #url(r'^listaUsuarios/$', UsuariosList.as_view(), name='listaUsuarios'),
    #url(r'^addUsuario$', 'addUsuario', name='addUsuario'),
    #url(r'^listarUsuarios/$', 'listaUsuarios', name='listaUsuarios'),
    
    # url(r'^blog/', include('blog.urls')),


)

apps/eventos/urls.py
from django.conf.urls import patterns, url
from apps.eventos.views import *



urlpatterns = patterns('apps.eventos.views',
    # Examples:
    #url(r'^panel$', 'panel', name='panel'),
    #url(r'^login$', 'iniciar_sesion', name='login'),
    #url(r'^', 'listaEgresados', name='listaEgresados'),
    url(r'^/$', 'listaEventos', name='listaEventos'),
    url(r'^/add$', 'addEvento', name='addEvento'),
    url(r'^/edit/(?P<evento_id>\d+)/$', 'editEvento', name='editEvento'),
    url(r'^/publicar/(?P<evento_id>\d+)/$', 'PublicarEvento', name='publicarEvento'),
    url(r'^/borrar/(?P<evento_id>\d+)/$', 'BorrarEvento', name='borrarEvento'),
    url(r'^/detail/(?P<evento_id>\d+)/$', 'detalleEvento', name='detailEvento'),
    url(r'^/listar/', 'evento_list'),
    #url(r'^egresado/addegresado/$', 'addEgresado', name='addEgresado'),
    #url(r'^listaUsuarios/$', UsuariosList.as_view(), name='listaUsuarios'),
    #url(r'^addUsuario$', 'addUsuario', name='addUsuario'),
    #url(r'^listarUsuarios/$', 'listaUsuarios', name='listaUsuarios'),
    
    # url(r'^blog/', include('blog.urls')),


)

apps/informes/urls.py
from django.conf.urls import patterns, url
from apps.informes.views import *
from wkhtmltopdf.views import PDFTemplateView



urlpatterns = patterns('apps.informes.views',
    # Examples:
    url(r'^/$', IndexInformeView.as_view(), name='indexInformes'),
    #url(r'^/pdf/$', MyPDF.as_view(), name='pdf'),
    url(r'^/graficos/$', Graficos.as_view(), name='graficos'),
    url(r'^/chrome/$', HomePageView.as_view(), name='cr'),
    url(r'^/grafico/(?P<numero>\d+)/$', GraficoDetalle.as_view(), name='graficoDetalle'),
    url(r'^/graficos/primergraficopdf/$', 'PrimerInformePdf', name='primerGrafico'),
    url(r'^/graficos/segundograficopdf/$', 'SegundoInformePdf', name='segundoGrafico'),
    url(r'^/graficos/tercerograficopdf/$', 'TerceroInformePdf', name='terceroGrafico'),
    url(r'^/graficos/cuartograficopdf/$', 'CuartoInformePdf', name='cuartoGrafico'),
    url(r'^/graficos/quintograficopdf/$', 'QuintoInformePdf', name='quintoGrafico'),
    url(r'^/graficos/sextograficopdf/$', 'SextoInformePdf', name='sextoGrafico'),
    url(r'^/graficos/septimograficopdf/$', 'SeptimoInformePdf', name='septimoGrafico'),
    url(r'^/graficos/octavograficopdf/$', 'OctavoInformePdf', name='octavoGrafico'),
    url(r'^/graficos/novenograficopdf/$', 'NovenoInformePdf', name='novenoGrafico'),
    url(r'^/graficos/decimograficopdf/$', 'DecimoInformePdf', name='decimoGrafico'),
    url(r'^/graficos/Undecimograficopdf/$', 'UnDecimoInformePdf', name='undecimoGrafico'),
    url(r'^/graficos/docegraficopdf/$', 'DoceInformePdf', name='doceGrafico'),
    url(r'^/graficos/trecegraficopdf/$', 'TreceInformePdf', name='treceGrafico'),
    url(r'^/graficos/catorcegraficopdf/$', 'CatorceInformePdf', name='catorceGrafico'),
    url(r'^/graficos/quincegraficopdf/$', 'QuinceInformePdf', name='quinceGrafico'),
    url(r'^/graficos/dieciseisgraficopdf/$', 'DieciseisInformePdf', name='dieciseisGrafico'),
    url(r'^/graficos/diecisietegraficopdf/$', 'DiecisieteInformePdf', name='diecisieteGrafico'),
    url(r'^/graficos/dieciochograficopdf/$', 'DieciochoInformePdf', name='dieciochoGrafico'),
    url(r'^/graficos/diecinuevegraficopdf/$', 'DiecinueveInformePdf', name='diecinueveGrafico'),
    #url(r'^encuesta/crear$', EncuestaCreateView.as_view(), name='crearEncuesta'),
    # url(r'^blog/', include('blog.urls')),


)

apps/usuarios/urls.py
from django.conf.urls import patterns, url
from apps.usuarios.views import *



urlpatterns = patterns('apps.usuarios.views',
    # Examples:
    url(r'^/$', 'usuarios', name='usuarios'),
    url(r'^/empresas/$', 'listaEmpresas', name='listaEmpresas'),
    url(r'^/egresado/detail/(?P<egresado_id>\d+)/$', 'detailEgresado', name='detailEgresado'),
    url(r'^/addEgresado/$', EgresadoCreateView.as_view(), name='addEgresado'),
    
    
    #url(r'^listaUsuarios/$', UsuariosList.as_view(), name='listaUsuarios'),
    #url(r'^addUsuario$', 'addUsuario', name='addUsuario'),
    #url(r'^listarUsuarios/$', 'listaUsuarios', name='listaUsuarios'),
    
    # url(r'^blog/', include('blog.urls')),


)

oveu/urls.py
from django.conf.urls import patterns, include, url
from apps.usuarios.views import *
from apps.blog.views import *
from apps.eventos.views import *
from apps.oferta.views import *

import settings
#import autocomplete_light
from django.contrib import admin
autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^confirm/(?P<key>\w+)/','apps.usuarios.views.confimar'),
    url(r'^dashboard/egresado/reenviarcodigo/(?P<id_usuario>\d+)/$', 'apps.usuarios.views.reenviarCodigo', name='reenviarCodigo'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^add/(?P<model_name>\w+)/?$', 'tekextensions.views.add_new_model'),
    url(r'^configurar$','apps.usuarios.views.instalar'),
    url(r'^configurar/programas/$','apps.usuarios.views.ProgramaConfFormView' , name='agregarProgramas'),
    url(r'^dashboard/programas/eliminar/(?P<programa_id>\d+)/$','apps.usuarios.views.eliminarPrograma' , name='eliminarPrograma'),
    # url(r'^dashboard/', include('apps.usuarios.urls', namespace='dashurl')),
    #url(r'^agregaregresado', 'apps.usuarios.views.addEgresado', name='Egre'),
    url(r'^dashboard/encuesta', include('apps.encuesta.urls', namespace='encuesta')),
    url(r'^dashboard/informes', include('apps.informes.urls', namespace='informes')),
    url(r'^addE', EgresadoCreateView.as_view()),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    url(r'^panel$', 'apps.usuarios.views.panel', name='panel'),
    url(r'^login$', 'apps.usuarios.views.iniciar_sesion', name='login'),
    url(r'^logout$', 'apps.usuarios.views.logout', name='logout'),
    url(r'^dashboard/egresados$', 'apps.usuarios.views.listaEgresados', name='listaEgresados'),
    url(r'^dashboard/$', 'apps.usuarios.views.dashboard', name='dashboard'),
    url(r'^dashboard/egresadosDesactualizados$', 'apps.usuarios.views.listaEgresadosDesactualizados', name='listaEgresadosDesactualizados'),
    url(r'^dashboard/usuarios/$', 'apps.usuarios.views.usuarios', name='usuarios'),
    #urls para empresas
    url(r'^dashboard/empresas/$', 'apps.usuarios.views.listaEmpresas', name='listaEmpresas'),
    url(r'^dashboard/empresa/(?P<empresa_id>\d+)/$', 'apps.usuarios.views.toggleEmpresa', name='toggleEmpresa'),
    url(r'^dashboard/addEmpresa/$', 'apps.usuarios.views.addEmpresa', name='addEmpresa'),
    #fin urls empresas
    #urls para eventos
    url(r'^dashboard/eventos', include('apps.eventos.urls',namespace='eventos')), 
    #url(r'^dashboard/eventos/$', 'apps.eventos.views.listaEventos', name='listaEventos'),
    #url(r'^dashboard/evento/add$', 'apps.eventos.views.addEvento', name='addEvento'),
    #url(r'^dashboard/evento/edit/(?P<evento_id>\d+)/$', 'apps.eventos.views.editEvento', name='editEvento'),
    #url(r'^dashboard/evento/detail/(?P<evento_id>\d+)/$', 'apps.eventos.views.detalleEvento', name='detailEvento'),
    #fin urls eventos
    url(r'^dashboard/addCoordinador$', 'apps.usuarios.views.addCoordinador', name='addCoordinador'),
    url(r'^dashboard/actualizarCoordinador$', CoordinadorUpdateView.as_view(), name='actualizarCoordinador'),
    
    url(r'^dashboard/egresado/addEgresado/$', EgresadoCreateView.as_view(), name='addEgresado'),
    url(r'^dashboard/egresado/edit/(?P<pk>\d+)/$', EgresadoUpdateView.as_view(), name='editEgresado'),
    url(r'^dashboard/egresado/eliminar/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.eliminarEgresado', name='eliminarEgresado'),
    url(r'^admin/', include(admin.site.urls)),
    #urls de blogs
    url(r'^', include('apps.blog.urls')),
    #dashboard portal web
    url(r'^dashboard/portal/addEntrada/$', 'apps.blog.views.addEntrada', name='addEntrada'),
    url(r'^dashboard/portal/editEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.editEntrada', name='editEntrada'),
    url(r'^dashboard/portal/delEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.delEntrada', name='delEntrada'),
    url(r'^dashboard/portal/addCategoria/$', 'apps.blog.views.addCategoria', name='addCategoria'),
    url(r'^dashboard/portal/listaCategoria/$', 'apps.blog.views.listaCategoria', name='listaCategoria'),
    url(r'^dashboard/portal/listaCategoria/edit/(?P<categorias_id>\d+)/$', 'apps.blog.views.editCategoria', name='editCategoria'),
    url(r'^dashboard/portal/listaCategoria/del/(?P<categorias_id>\d+)/$', 'apps.blog.views.delCategoria', name='delCategoria'),
    url(r'^dashboard/portal/listaEntrada/$', 'apps.blog.views.listaEntrada', name='listaEntrada'),

    #urls de oferta laboral
    url(r'^dashboard/oferta', include('apps.oferta.urls')),
    #urls de correo
    url(r'^dashboard/correo', include('apps.correo.urls', namespace='correo')),  
    #urls de tinycme 
    url(r'^tinymce/', include('tinymce.urls')),
    #url programas
    url(r'^dashboard/programas/addPrograma$', ProgramaFormView.as_view(), name='addPrograma'),
    url(r'^dashboard/programas/list/$', ProgramaListView.as_view(), name='listaProgramas'),
    url(r'^dashboard/programas/edit/(?P<pk>\d+)/$', 'apps.usuarios.views.ProgramaUpdate', name='updatePrograma'),
    #fin url
    url(r'^dashboard/helper/busquedaAjax/', 'apps.usuarios.views.busquedaAjax', name='busquedaAjax'),
    url(r'^dashboard/egresado/detail/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.detailEgresado', name='detailEgresado'),
)

oveu/templates/usuarios/actualizarCoordinador.html
{% extends "usuarios/basePanel.html" %}
{% load bootstrap %}

{% if request.session.nombre_usuario %}
    {% block user %}
        {% include "usuarios/user-info.html" %}
    {% endblock %}
{% endif %}
{% block contenido_panel %}

	<div class="row" style="width:80%;margin:0 auto;">
                <div class="col-sm-10">
                    <h2 style="color:#c33833;font-weight:bold;padding-bottom: 10px;">Actualizar Coordinador</h2>

                    <hr />

                    {% if mensaje %}
                        <div class="alert alert-{{clase}}">
                        <a class="close" data-dismiss="alert">x</a>
                        {{ mensaje }}
                    </div>
                    {% endif %}


                    <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                        <h3 style="text-align:center">Quieres cambiar la contraseña?</h3>
                        {{ usuario_form|bootstrap_horizontal}}
                        <br>
                        <h3 style="text-align:center">Edita tu informacion</h3>
                        {{ form|bootstrap_horizontal }}
                        
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-lg-6 col-sm-10">
                                <input type="submit" class="btn btn-primary" value="Actualizar" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
{% endblock %}

oveu/templates/usuarios/baseLogin.html
<html>
<head>
	<title></title>
</head>
<body>
<h1>hola Django!!</h1>
</body>
</html>

oveu/templates/usuarios/basePanel.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{% block title %}Egresados Administracion{% endblock %}</title>
	<!--<link href="{{ STATIC_URL }}css/font-awesome.min.css" rel="stylesheet">-->
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/normalize.css">
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery.datetimepicker.css">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/style-tablesorter.css">
	
	{% block estaticos %}
	{% endblock %}
</head>
<body >
<div class="contenedor">
	<header>
		<div class="logo" style="padding:12px 0;">
			<a href="{% url 'dashboard' %}" style="color:white;margin-left:5px;font-size:25px;text-decoration:none;">Egresados Admin</a>
		</div>
		<div class="menubar">
			<a href="{% url 'informes:graficoDetalle' '1' %}">Informes</a>	
			<a href="{% url 'usuarios' %}">Gestion de Usuarios</a>	

		</div>
		<div class="helperButtons">
			<!--<a class="buscar-icon" href="#"></a>
			<a class="campanita-icon"  href="#"></a>
			<a class="configuracion-icon" href="#"></a>-->
			<a class="salir" title="Salir del sistema" href="{% url 'logout' %}"></a>
		</div>
		{% block user %}
			
		{% endblock %}
		

	
		
	</header>

	<aside class="navegacion">
		{% include 'usuarios/menu.html' %}

	</aside>
	<div class="panelContenido">

		{% block contenido_panel %}

		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, atque, unde facere error ducimus laudantium obcaecati ullam optio eius maxime magnam blanditiis natus similique veritatis sed quasi modi aspernatur quae. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero, quia quasi et doloribus odio culpa itaque mollitia provident blanditiis nihil? Aliquam, quia deleniti ut est nemo non reprehenderit quod blanditiis.</p>
		{% endblock%}
	</div>

</div>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.ssd-vertical-navigation.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.tablesorter.js"></script>
<script>
	
	$(function() {

	    $('#leftNavigation').ssdVerticalNavigation();

	});
            
            $("#flechita-id" ).on( "click", function() {

            	$("#menu-flechita-id").show();
			  
			});

			var openDiv;

			function toggleDiv(divID) {
			    $("#" + divID).fadeToggle(200, function() {
			        openDiv = $(this).is(':visible') ? divID : null;
			    });
			}

			$(document).click(function(e) {
			    if (!$(e.target).closest('#'+openDiv).length) {
			        toggleDiv(openDiv);
			    }
			});



       

</script>

{% block js %}
{% endblock %}

</body>
</html>

oveu/templates/usuarios/crearEmpresaU.html
{% extends "usuarios/basePanel.html" %}
{% load bootstrap %}
{% block user %}
    {% include "usuarios/user-info.html" %}
{% endblock %}
{% block contenido_panel %}

	<div class="row" style="width:80%;margin:0 auto;">
                <div class="col-sm-10">
                    <h2>Registrar Empresa Usuario</h2>

                    <hr />

                    <form class="form-horizontal" method="POST">
                    	{% csrf_token %}
                        {{ form|bootstrap_horizontal }}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-lg-6 col-sm-10">
                                <input type="submit" class="btn btn-primary" value="Registrar" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
{% endblock %}

oveu/templates/usuarios/ejemplo.html
<html>
<head>
	<title>{{ title }}</title>
</head>
<body>
	<h1> {{ nombre }}</h1>

	{% for l in lista %}
		{% if l == 2 %}
			<strong>es Par</strong>
		{% else %}
			<h2> {{ l }}</h2>

		{% endif %}
	{% endfor %}

</body>
</html>

oveu/templates/usuarios/gestionUsuarios.html
{% extends 'usuarios/basePanel.html' %}
{% block user %}
	{% include "usuarios/user-info.html" %}
{% endblock %}
{% block contenido_panel %}
	<div style="width:90%; margin:0 auto;">

		<h2 style="color:#c33833;font-weight:bold;padding-bottom: 10px;">Lista de Usuarios</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Tipo Usuarios</th>
					<th>Cantidad</th>					
				</tr>
			</thead>
			<tbody style="font-weigth:none">
				<tr>
						<th><a href="{% url 'listaEgresados' %}">Egresados</a></th>
						{% if egresados == 0 %}
							<th> No hay usuarios </th>
						{% else %}
							<th>{{ egresados }}</th>
						{% endif %}

				</tr>	
				<tr>
						<th><a href="{% url 'listaEmpresas' %}" >Empresas</a></th>
						{% if empresa == 0 %}
							<th> No hay Empresas </th>
						{% else %}
							<th>{{ empresa }}</th>
						{% endif %}
						
				</tr>
				<tr>
						<th><a href="#" >Administrador</a></th>
						{% if administrador == 0 %}
							<th> No hay usuarios </th>
						{% else %}
							<th>{{ administrador }}</th>
						{% endif %}

				</tr>
				</tbody>
		</table>
	</div>		 
	
{% endblock %}

oveu/templates/usuarios/menu.html
<ul id="leftNavigation">
        {% for m in menu %}
            
        <li {% if m.active %}class="active"{% endif %}>
            <a href="#"><i style="margin:-3px" class="fa {{m.icono }} leftNavIcon"></i>  {{m.name}}</a>
            <ul>
                {% for sm in m.submenu %}
                <li>
                    <a href="{{ sm.surl }}"><i class="fa fa-angle-right leftNavIcon"></i> {{sm.sname}}</a>
                </li>
                {% endfor %}
            </ul>
            
        </li>
        
        {% endfor %}
<!--
        <li class="active">
            <a href="#"><i class="fa fa-male leftNavIcon"></i> Egresados</a>
            <ul>
                <li>
                    <a href="{% url 'listaEgresados' %}"><i class="fa fa-angle-right leftNavIcon"></i> Listar Egresados</a>
                </li>
                <li>
                    <a href="{% url 'listaEgresadosDesactualizados' %}"><i class="fa fa-angle-right leftNavIcon"></i> Listar Egresados Desactualizados</a>
                </li>
                <li>
                    <a href="{% url 'addEgresado' %}"><i class="fa fa-angle-right leftNavIcon"></i> Registrar Egresado</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#"><i class="fa fa-keyboard-o leftNavIcon"></i> Portal Web</a>
            <ul>
                <li>
                    <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Listar noticia</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Publicar noticia</a>
                </li>
                
            </ul>
        </li>
        <li>
            <a href="#"><i class="fa fa-truck leftNavIcon"></i> Encuestas</a>
            <ul>
                <li>
                    <a href="{% url 'encuesta:crearEncuesta' %}"><i class="fa fa-angle-right leftNavIcon"></i> Crear Encuesta</a>
                </li>
                <li>
                    <a href="{% url 'encuesta:listaEncuesta' %}"><i class="fa fa-angle-right leftNavIcon"></i> Listar Encuestas</a>
                </li>
                
            </ul>
        </li>
        <li>
            <a href="#"><i class="fa fa-envelope-o leftNavIcon"></i> Eventos</a>
            <ul>
                <li>
                    <a href="{% url 'eventos:addEvento' %}"><i class="fa fa-angle-right leftNavIcon"></i> Crear Evento</a>
                </li>
                <li>
                    <a href="{% url 'eventos:listaEventos' %}"><i class="fa fa-angle-right leftNavIcon"></i> Listar eventos</a>
                </li>
            </ul>
        </li>-->
        
        
    


    </ul>



	<!--<a href="{% url 'listaEgresados' %}"><span class="egresado">Egresados</span></a>
	<a href="{% url 'listaEntrada' %}"><span class="blog">Portal Web</span></a>
	<a href="{% url 'encuesta:listaEncuesta' %}"><span class="encuesta">Encuestas</span></a>
	<a href="{% url 'eventos:listaEventos' %}"> <span class="calendar">Eventos</span></a>
	<a href="{% url 'correo:indexCorreo' %}"><span class="message">Correo</span></a>
	<a href="{% url 'listaOfertaLaboral' %}"><span class="promote">Oferta laboral</span></a>
	<a href="{% url 'listaEmpresas' %}"><span class="empresa">Empresa</span></a>
	-->
		

oveu/templates/usuarios/p.html
clave
<br>
{{ pass }}
<br>


oveu/templates/usuarios/updatePrograma.html
{% extends "usuarios/basePanel.html" %}
{% load bootstrap %}
{% block user %}
    {% include "usuarios/user-info.html" %}
{% endblock %}
{% block contenido_panel %}

	<div class="row" style="width:60%;margin:0 auto;">
                <div class="span12">
                    <h2 class="titulos">Editar Programa</h2>

                    <hr />

                    <form class="form" method="POST">
                    	{% csrf_token %}
                        {{ form|bootstrap }}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <input type="submit" class="btn btn-primary" value="Guardar" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
{% endblock %}