apps/eventos/urls.py
from django.conf.urls import patterns, url
from apps.eventos.views import *



urlpatterns = patterns('apps.eventos.views',
    # Examples:
    #url(r'^panel$', 'panel', name='panel'),
    #url(r'^login$', 'iniciar_sesion', name='login'),
    #url(r'^', 'listaEgresados', name='listaEgresados'),
    url(r'^/$', 'listaEventos', name='listaEventos'),
    url(r'^/add$', 'addEvento', name='addEvento'),
    url(r'^/edit/(?P<evento_id>\d+)/$', 'editEvento', name='editEvento'),
    url(r'^/publicar/(?P<evento_id>\d+)/$', 'PublicarEvento', name='publicarEvento'),
    url(r'^/borrar/(?P<evento_id>\d+)/$', 'BorrarEvento', name='borrarEvento'),
    url(r'^/detail/(?P<evento_id>\d+)/$', 'detalleEvento', name='detailEvento'),
    url(r'^/listar/', 'evento_list'),
    #url(r'^egresado/addegresado/$', 'addEgresado', name='addEgresado'),
    #url(r'^listaUsuarios/$', UsuariosList.as_view(), name='listaUsuarios'),
    #url(r'^addUsuario$', 'addUsuario', name='addUsuario'),
    #url(r'^listarUsuarios/$', 'listaUsuarios', name='listaUsuarios'),
    
    # url(r'^blog/', include('blog.urls')),


)

oveu/urls.py
from django.conf.urls import patterns, include, url
from apps.usuarios.views import *
from apps.blog.views import *
from apps.eventos.views import *
from apps.oferta.views import *

import settings
#import autocomplete_light
from django.contrib import admin
autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^confirm/(?P<key>\w+)/','apps.usuarios.views.confimar'),
    url(r'^dashboard/egresado/reenviarcodigo/(?P<id_usuario>\d+)/$', 'apps.usuarios.views.reenviarCodigo', name='reenviarCodigo'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^add/(?P<model_name>\w+)/?$', 'tekextensions.views.add_new_model'),
    url(r'^configurar$','apps.usuarios.views.instalar'),
    url(r'^configurar/programas/$','apps.usuarios.views.ProgramaConfFormView' , name='agregarProgramas'),
    url(r'^dashboard/programas/eliminar/(?P<programa_id>\d+)/$','apps.usuarios.views.eliminarPrograma' , name='eliminarPrograma'),
    # url(r'^dashboard/', include('apps.usuarios.urls', namespace='dashurl')),
    #url(r'^agregaregresado', 'apps.usuarios.views.addEgresado', name='Egre'),
    url(r'^dashboard/encuesta', include('apps.encuesta.urls', namespace='encuesta')),
    url(r'^dashboard/informes', include('apps.informes.urls', namespace='informes')),
    url(r'^addE', EgresadoCreateView.as_view()),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    url(r'^panel$', 'apps.usuarios.views.panel', name='panel'),
    url(r'^login$', 'apps.usuarios.views.iniciar_sesion', name='login'),
    url(r'^logout$', 'apps.usuarios.views.logout', name='logout'),
    url(r'^dashboard/egresados$', 'apps.usuarios.views.listaEgresados', name='listaEgresados'),
    url(r'^dashboard/$', 'apps.usuarios.views.dashboard', name='dashboard'),
    url(r'^dashboard/egresadosDesactualizados$', 'apps.usuarios.views.listaEgresadosDesactualizados', name='listaEgresadosDesactualizados'),
    url(r'^dashboard/usuarios/$', 'apps.usuarios.views.usuarios', name='usuarios'),
    #urls para empresas
    url(r'^dashboard/empresas/$', 'apps.usuarios.views.listaEmpresas', name='listaEmpresas'),
    url(r'^dashboard/empresa/(?P<empresa_id>\d+)/$', 'apps.usuarios.views.toggleEmpresa', name='toggleEmpresa'),
    url(r'^dashboard/addEmpresa/$', 'apps.usuarios.views.addEmpresa', name='addEmpresa'),
    #fin urls empresas
    #urls para eventos
    url(r'^dashboard/eventos', include('apps.eventos.urls',namespace='eventos')), 
    #url(r'^dashboard/eventos/$', 'apps.eventos.views.listaEventos', name='listaEventos'),
    #url(r'^dashboard/evento/add$', 'apps.eventos.views.addEvento', name='addEvento'),
    #url(r'^dashboard/evento/edit/(?P<evento_id>\d+)/$', 'apps.eventos.views.editEvento', name='editEvento'),
    #url(r'^dashboard/evento/detail/(?P<evento_id>\d+)/$', 'apps.eventos.views.detalleEvento', name='detailEvento'),
    #fin urls eventos
    url(r'^dashboard/addCoordinador$', 'apps.usuarios.views.addCoordinador', name='addCoordinador'),
    url(r'^dashboard/actualizarCoordinador$', CoordinadorUpdateView.as_view(), name='actualizarCoordinador'),
    
    url(r'^dashboard/egresado/addEgresado/$', EgresadoCreateView.as_view(), name='addEgresado'),
    url(r'^dashboard/egresado/edit/(?P<pk>\d+)/$', EgresadoUpdateView.as_view(), name='editEgresado'),
    url(r'^dashboard/egresado/eliminar/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.eliminarEgresado', name='eliminarEgresado'),
    url(r'^admin/', include(admin.site.urls)),
    #urls de blogs
    url(r'^', include('apps.blog.urls')),
    #dashboard portal web
    url(r'^dashboard/portal/addEntrada/$', 'apps.blog.views.addEntrada', name='addEntrada'),
    url(r'^dashboard/portal/editEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.editEntrada', name='editEntrada'),
    url(r'^dashboard/portal/delEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.delEntrada', name='delEntrada'),
    url(r'^dashboard/portal/addCategoria/$', 'apps.blog.views.addCategoria', name='addCategoria'),
    url(r'^dashboard/portal/listaCategoria/$', 'apps.blog.views.listaCategoria', name='listaCategoria'),
    url(r'^dashboard/portal/listaCategoria/edit/(?P<categorias_id>\d+)/$', 'apps.blog.views.editCategoria', name='editCategoria'),
    url(r'^dashboard/portal/listaCategoria/del/(?P<categorias_id>\d+)/$', 'apps.blog.views.delCategoria', name='delCategoria'),
    url(r'^dashboard/portal/listaEntrada/$', 'apps.blog.views.listaEntrada', name='listaEntrada'),

    #urls de oferta laboral
    url(r'^dashboard/oferta', include('apps.oferta.urls')),
    #urls de correo
    url(r'^dashboard/correo', include('apps.correo.urls', namespace='correo')),  
    #urls de tinycme 
    url(r'^tinymce/', include('tinymce.urls')),
    #url programas
    url(r'^dashboard/programas/addPrograma$', ProgramaFormView.as_view(), name='addPrograma'),
    url(r'^dashboard/programas/list/$', ProgramaListView.as_view(), name='listaProgramas'),
    url(r'^dashboard/programas/edit/(?P<pk>\d+)/$', 'apps.usuarios.views.ProgramaUpdate', name='updatePrograma'),
    #fin url
    url(r'^dashboard/helper/busquedaAjax/', 'apps.usuarios.views.busquedaAjax', name='busquedaAjax'),
    url(r'^dashboard/egresado/detail/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.detailEgresado', name='detailEgresado'),
)

apps/eventos/models.py
from django.db import models
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
from apps.usuarios.models import Administrador, Egresado
import datetime

class Evento(models.Model):
	titulo = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_inicio = models.DateTimeField()
	fecha_fin = models.DateTimeField()
	imagen = models.ImageField(upload_to='img_evento', blank=True, null=True)
	telefono = models.CharField(max_length=20)
	correo = models.EmailField()
	direccion = models.CharField(max_length=120)
	estado = models.BooleanField(default=False, verbose_name='Publicado')
	coordinador = models.ForeignKey(Administrador)
	fecha_creacion = models.DateTimeField(auto_now=True,auto_now_add=True, default=datetime.datetime.now())
	enviado = models.BooleanField(default=False, verbose_name='Correo enviado?')

	def __unicode__(self):
		return self.titulo

# borrar imagen del disco duro
@receiver(pre_delete, sender=Evento)
def post_pre_delete_handler(sender, instance, **kwargs):
	instance.imagen.delete(False)


class Asistente(models.Model):
	"""docstring for Asistente"""
	egresado = models.ForeignKey(Egresado)
	evento = models.ForeignKey(Evento)
	

apps/eventos/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from .models import *


class EventoForm(ModelForm):
	
	class Meta:
		model = Evento
		exclude = ['coordinador','enviado']
		labels = {
			'estado': ('Publicar?'),
			'fecha_fin':('Fecha de finalizacion'),
		}
		help_texts = {
            'imagen': ('La imagen debe tener un ancho de 518 pixel, para mayor compatibilidad con el diseño, si no el diseño se podria ver mal.'),
        }

    

apps/eventos/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.core.urlresolvers import reverse
from apps.eventos.forms import *
from apps.eventos.models import *
from apps.usuarios.decorators import loginRequired
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from apps.eventos.filters import EventoFilter
from .tasks import SendEmailEventTask
from django.core import serializers
import json
from django.conf import settings



#prueba de django_filters

def evento_list(request):
    f = EventoFilter(request.GET, queryset=Evento.objects.all())
    return render(request, 'eventos/template.html', {'filter': f})


@loginRequired
def listaEventos(request):
	f = EventoFilter(request.GET, queryset=Evento.objects.all())
	if request.method == 'POST':
		query = request.POST.get('query')
		busqueda = request.POST.get('busqueda')
		estado = request.POST.get('estado')
		print query
		if query and busqueda and estado:
			if busqueda == 'titulo':
				if estado == 'todos':
					evento = Evento.objects.filter(titulo__istartswith=query)
				if estado == 'publicados':
					evento = Evento.objects.filter(titulo__istartswith=query).filter(estado=True)
				if estado == 'sinpublicar':
					evento = Evento.objects.filter(titulo__istartswith=query).filter(estado=False)
			if busqueda == 'descripcion':
				if estado == 'todos':
					evento = Evento.objects.filter(descripcion__icontains=query)
				if estado == 'publicados':
					evento = Evento.objects.filter(descripcion__icontains=query).filter(estado=True)
				if estado == 'sinpublicar':
					evento = Evento.objects.filter(descripcion__icontains=query).filter(estado=False)

	else:
		evento = Evento.objects.all()

	return render_to_response('eventos/evento_list.html',{'eventos':evento, 'filter': f}, context_instance=RequestContext(request))
	
@loginRequired
def addEvento(request):
		if request.method == 'POST':
			form = EventoForm(request.POST, request.FILES)
			#verificamos si es valido
			if form.is_valid():
				a = Administrador.objects.get(pk=request.session['id_coordinador'])
				evento = form.save(commit=False)
				evento.coordinador = a
				#recogemos a quien le enviaremos la invitacion al evento por correo
				destinatarios = request.POST.get('envioCorreo',)
				asunto = request.POST.get('asunto',)
				
				if destinatarios != 0:
					if evento.estado:
						link = 'http://localhost:8000/evento/ver/%s' % (evento.id)

						SendEmailEventTask.delay(destinatarios, evento.titulo, evento.descripcion, evento.fecha_inicio.strftime('%d-%m-%Y %H:%M'), evento.fecha_fin.strftime('%d-%m-%Y %H:%M'), evento.telefono, evento.correo, link, asunto, evento.imagen.url)
						evento.enviado = True
					
				evento.save()
				return 	HttpResponseRedirect(reverse('eventos:listaEventos'))
			else:
				accion ="Crear"
				return render(request, 'eventos/addEvento.html',{'form' :form, 'accion':accion})
		
		else:
			form = EventoForm()
			accion ="Crear"
		return render(request, 'eventos/addEvento.html',{'form' :form, 'accion':accion})

@loginRequired
def editEvento(request, evento_id):
	e = get_object_or_404(Evento,pk=evento_id)
	if request.method == 'POST':
		form = EventoForm(request.POST, request.FILES)
		if form.is_valid():
			#Creo una isntancia de evento
			e.titulo = form.cleaned_data['titulo']
			e.descripcion = form.cleaned_data['descripcion']
			e.fecha_inicio = form.cleaned_data['fecha_inicio']
			e.fecha_fin = form.cleaned_data['fecha_fin']
			e.telefono = form.cleaned_data['telefono']
			e.correo = form.cleaned_data['correo']
			e.direccion = form.cleaned_data['direccion']
			imagen = form.cleaned_data['imagen']
			if imagen:
				e.imagen = imagen
			e.estado = form.cleaned_data['estado']
			a = Administrador.objects.get(pk=request.session['id_coordinador'])
			e.coordinador = a
			#recogemos a quien le enviaremos la invitacion al evento por correo
			destinatarios = request.POST.get('envioCorreo',)
			asunto = request.POST.get('asunto',)
			if not e.enviado:
				if destinatarios != 0:
					evento = e
					if evento.estado:
						link = 'http://localhost:8000/evento/ver/%s' % (evento.id)

						SendEmailEventTask.delay(destinatarios, evento.titulo, evento.descripcion, evento.fecha_inicio.strftime('%d-%m-%Y %H:%M'), evento.fecha_fin.strftime('%d-%m-%Y %H:%M'), evento.telefono, evento.correo, link, asunto, evento.imagen.url)
						e.enviado = True
			
			evento = e.save()

			return 	HttpResponseRedirect(reverse('eventos:listaEventos'))

	if request.method == 'GET':
		form = EventoForm(initial={
									'titulo': e.titulo,
									'descripcion': e.descripcion,
									'fecha_inicio': e.fecha_inicio,
									'fecha_fin': e.fecha_fin,
									'imagen': e.imagen,
									'estado': e.estado,
									'telefono': e.telefono,
									'correo': e.correo,
									'direccion': e.direccion
									
			})
	
		accion = "Editar"
		return render(request, 'eventos/addEvento.html', {'form': form, 'accion':accion, 'evento_object':e})

@loginRequired
def detalleEvento(request, evento_id):
	e = get_object_or_404(Evento,pk=evento_id)
	asistentes = Asistente.objects.filter(evento=e).count()
	return render(request, 'eventos/detalleEvento.html', {'evento':e, 'asistentes':asistentes})
	

@loginRequired
def PublicarEvento(request, evento_id):
	e = get_object_or_404(Evento,pk=evento_id)
	e.estado = True
	e.save()
	return HttpResponseRedirect(reverse('eventos:listaEventos'))

@loginRequired
def BorrarEvento(request, evento_id):
	e = get_object_or_404(Evento,pk=evento_id)
	e.delete()
	return HttpResponseRedirect(reverse('eventos:listaEventos'))

oveu/templates/eventos/addEvento.html
{% extends "usuarios/basePanel.html" %}
{% load bootstrap3 %}
{% block user %}
  {% include "usuarios/user-info.html" %}
{% endblock %}
{% block contenido_panel %}

	<div class="row" style="width:80%;margin:5px auto;">
                <div class="col-sm-8">
                    <h2 class="titulos">{{ accion }} Evento</h2>

                    <hr />
                    <form class="form" method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                        {% bootstrap_form form %}
                        
                        {% if not evento_object.enviado %}

                                                  
                        {% if not evento_object.estado %}
                              <br>
                        <h4>A quien le quieres enviar la informacion de este evento?</h4>
                        <small class="text-danger">Para poder seleccionar a quien enviar invitacion a este evento, debes marcar la opcion de publicar. </small>
                        <br>
                        <select name="envioCorreo" id="envio" disabled>    
                            <option value="0" default>No enviar correos</option>                   
                            <option value="todos">Todos (Empresa y Egresado)</option>
                            <option value="empresa">Solo Empresa</option>
                            <option value="egresado">Solo Egresado</option>
                        </select>

                        <br>
                        <br>
                        <div class="form-group" id="dAsunto" style="display:none">
                            <label>Asunto</label>
                            <input type="text" class="form-control" id="asunto" name="asunto" placeholder="Asunto">
                            <p class="help-block">Recuerda que si envias diferentes correos con el mismo asunto, los servicios de email los marcarian como "correo no deseado"</p>
                        </div>
                        <br>
                        <br>
                       

                        {% endif %}
    {% endif %}
                        

                            <br>
                             <div class="form-actions">
                                <input type="submit" name="guardar" value="Guardar" class="btn btn-success">
                            </div>

                    </form>
                    <br>
                    <br>
                 </div>
    </div>
{% endblock %}
{% block js %}
<script src="{{ STATIC_URL }}js/jquery.datetimepicker.js"></script>
<script>

$(document).ready(function() {
    
        $('#id_fecha_inicio').datetimepicker({
             lang:'es',
             timepicker:true,
             format:'d/m/Y H:i'
        });
         $('#id_fecha_fin').datetimepicker({
             lang:'es',
             timepicker:true,
             format:'d/m/Y H:i'
        });
         $( "#id_estado" ).click(function() {
            if ($('#id_estado').is(':checked')) {

                $('select[name="envioCorreo"]').removeAttr('disabled');

            }else{

                $('#envio').val("0");
                $('select[name="envioCorreo"]').attr('disabled', 'disabled');
                $('#asunto').val('')
            };
         });
         $('select[name="envioCorreo"]').change(function() {
              if($('select[name="envioCorreo"]').val()==0){
                $('#asunto').val('')
                $('#asunto').removeAttr('required');
                $('#dAsunto').hide();
              }else{

                $('#dAsunto').show();

                $('#asunto').attr('required', '');
                
              }
        });
         
         
});

</script>

{% endblock %}

oveu/templates/eventos/detalleEvento.html
{% extends "usuarios/basePanel.html" %}
{% block user %}
	{% include "usuarios/user-info.html" %}
{% endblock %}
{% block contenido_panel %}

		
	<div class="container">
		<div class="imagen-evento">
			<img class="img-responsive" src="/media/{{ evento.imagen }}" alt="">
		</div>
		<div class="descripcion-evento">
			<h3> {{ evento.titulo }} </h3>
			<p>
				{{ evento.descripcion }}
			</p>
			<div class="fechas">
				<div class="fecha-ini">
					<span class="label-fecha"> <i class="fa fa-calendar"></i> Fecha Inicio:</span>
					<span> {{ evento.fecha_inicio|date:'N j, Y f a'}} </span>
				</div>
				<div class="fecha-fin">
					<span class="label-fecha"><i class="fa fa-calendar"></i> Fecha Fin:</span>
					<span> {{ evento.fecha_fin|date:'N j, Y f a'}} </span></div>
				
			</div>
			<div>
				<label >Direccion:</label>
				<span>{{ evento.direccion }}</span>
				<br>
				<label >Telefono:</label>
				<span>{{ evento.telefono }}</span>
				<br>
				<label >Correo:</label>
				<span>{{ evento.correo }}</span>
				<br>
				<label >Estado:</label>
				{% if evento.estado %}
					<span> Evento Publicado</span>
				{% else %}
					<span> Evento sin publicar</span>
				{% endif %}
				<br>
				<label >Cantidad de asistentes:</label>
				<span>{{ asistentes }}</span>

			</div>
			<br>
			<div class="links">
				{% if evento.estado %}
					
				{% else %}
					<a href="{% url 'eventos:publicarEvento' evento.id %}" class="btn btn-default">Publicar</a>
				{% endif %}
				<a href="{% url 'eventos:editEvento' evento.id %}" class="btn btn-default">Editar </a>
				<a href="{% url 'eventos:borrarEvento' evento.id %}" class="btn btn-danger">Borrar</a>
			</div>
		</div>
		
			 
	</div>
	
	
{% endblock %}
{% block js %}
	<script>
		
		$('#buscar').on('click', busqueda);

		function busqueda () {
		var col = $('select').val();
		var caja = $('#text').val();
		
		$.ajax({
			data: {'col': col, 'caja':caja},
			url:'helper/busquedaAjax/',
			type: 'get',

		});
		
		}

	</script>
{% endblock %}

oveu/templates/eventos/evento_list.html
{% extends "usuarios/basePanel.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% block estaticos  %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.css">
{% endblock %}
{% block user %}
	{% include "usuarios/user-info.html" %}
{% endblock %}
{% block contenido_panel %}
		
		<div style="margin:0 1% 2px 1%;border-radius: 6px;background:#f2f2f2;overflow:hidden;padding:10px">
		
		<a href="#" id="clickSearch" style="font-size:23px; color:#c33833;margin-left: 10px;text-decoration:none;"><i class="fa fa-search"></i> Buscar</a>	
				
				<div class="" style="float:right;margin-right:15px">
					<a href="{% url 'eventos:addEvento' %}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Crear Evento</a>	
				</div>
		</div>

		<div id="busqueda" style="width:50%;margin: 10px 40px; display:none;font-size:10px;">
			<h2 class="titulos">Busqueda</h2>
			<form action="" method="get">
        {{ filter.form|bootstrap }}
        <input type="submit" class="btn btn-primary"/>
    </form>
    <br>
    <br>

</div>
		
	<div style="width:90%; margin:0 auto">
		<h2 class="titulos">Lista de Eventos</h2>
		<table id="myTable" class="table table-hover tablesorter" style="font-size:13px">
			<thead>
				<tr>
					<th style="width:232px">Titulo</th>
					<th style="width:200px">Descripcion</th>
					<th>Fecha Inicio</th>
					<th>Fecha Finalizacion</th>
					<th>Estado</th>
					<th style="width:150px">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for evento in filter %}

				
				<tr>
						<th>{{ evento.titulo }}</th>
						<th>{{ evento.descripcion|truncatechars:100 }}</th>
						<th>{{ evento.fecha_inicio|date:'m/d/Y f a' }}</th>
						<th>{{ evento.fecha_fin|date:'m/d/Y f a' }}</th>
						<th>{% if evento.estado %}
							Publicado
						
						{% else %}
							<a href="{% url 'eventos:publicarEvento' evento.id %}" class="btn btn-default btn-sm">Publicar</a>
						{% endif %}
					</th>

						<!--{% if egresados.usuario.estado == True %}
							<th><i class="fa fa-check"></i></th>
						{% else %}
							<th><i class="fa fa-ban"></i></th>
						{% endif %}-->
						<th><a href="{% url 'eventos:editEvento' evento.id %}" class="btn btn-default btn-sm">Editar</a>
						<a href="{% url 'eventos:detailEvento' evento.id %}" class="btn btn-default btn-sm">Ver</a>
							<a href="{% url 'eventos:borrarEvento' evento.id %}" class="btn btn-danger btn-sm confirmation">Borrar</a>
						</th>

					</tr>
				
				{% empty %}
					<tr><th> No hay Egresados</th><th></th><th></th><th></th><th><th></th></th></tr>
				{% endfor %}

			</tbody>
		</table>
		
		</div>
	<!--<div class="container">

		<legend><h2 style="color:#c33833;font-weight:bold; margin-top:0; padding-top:0">Lista de Eventos</h2></legend>
			{% for evento in eventos %}
			<div class="content_eventos">
				<div class="imagen">
					<img class="img-responsive" src="/media/{{evento.imagen}}" alt="Imagen">
				</div>
				
				<div class="descripcion">
					<div class="title">
						<h2> {{ evento.titulo }} </h2>
					</div>
					<p>{{ evento.descripcion|truncatechars:200 }}  </p>
					{% if evento.estado == False %}
						<span> Evento sin Publicar </span>
					{% else %}			
						<span> Evento Publicado </span>
					{% endif %}

					<div class="otro">
						<div class="fechas">
							<div class="fecha_inicio">
								<span class="texto"><i class="fa fa-calendar"></i> Fecha Inicio:</span>
								<span class="fecha"> {{ evento.fecha_inicio|date:'N j, Y f a'}}</span></div>
							<div class="fecha_fin">
								<span class="texto"><i class="fa fa-calendar"></i> Fecha Finalizacion:</span>
								<span class="fecha"> {{ evento.fecha_fin|date:'N j, Y f a' }}</span>
							</div>
															
						</div>

						<div class="links">
							<a href="{% url 'eventos:editEvento' evento.id %}" class="btn btn-default btn-sm">Editar</a>
							{% if evento.estado %}
								
							{% else %}
								<a href="{% url 'eventos:publicarEvento' evento.id %}" class="btn btn-default btn-sm">Publicar</a>
							{% endif %}
							<a href="{% url 'eventos:detailEvento' evento.id %}" class="btn btn-default btn-sm">Ver</a>
							<a href="{% url 'eventos:borrarEvento' evento.id %}" class="btn btn-danger btn-sm">Borrar</a>

						</div>
						
					</div>
					

				</div>
			</div>
			{% empty %}
				<h3>No Hay eventos para mostrar</h3>
				
			{% endfor %}
			 
		</div>

		
	-->

{% endblock %}
{% block js %}
<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.js"></script>
<script src="{% static  '/static/js/bootstrap-confirmation.js'%}"></script>
	<script>
		$(document).ready(function() 
	    { 
	    	$('#myTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/a5734b29083/i18n/Spanish.json"
            }
        });
	        $("#myTable").tablesorter({sortList: [[0,0]],headers:{ 4: { sorter: false},5: { sorter: false}}}); 
	    });
		
		$(document).ready(function() 
	    { 
	    	$("#clickSearch").click(function() {
	    		$("#busqueda").toggle('slow');
	    	});

	    	$('.confirmation').confirmation({'title':"Esta seguro que quiere borrar este evento?", 'placement':"top", 'singleton':true, 'popout':true, 'btnOkLabel':"Eliminar", 'btnCancelLabel':"Cancelar"});

	    });
		

	</script>
{% endblock %}

oveu/templates/eventos/template.html
{% extends "usuarios/basePanel.html" %}



{% block user %}
  {% include "usuarios/user-info.html" %}
{% endblock %}

{% block contenido_panel %}
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter %}
        {{ obj.name }} - ${{ obj.price }}<br />
    {% endfor %}
{% endblock %}