apps/encuesta/urls.py
from django.conf.urls import patterns, url
from apps.encuesta.views import *



urlpatterns = patterns('apps.encuesta.views',
    # Examples:
    url(r'^/$','encuesta_list', name='listaEncuesta'),
    url(r'^/export/(?P<encuesta_id>\d+)/$','exportPreguntasA', name='export'),   
    url(r'^/helpers/editaropcion/(?P<pk>\d+)/$', 'editarOpcion', name='editOpcion'),
    url(r'^/helpers/editarpregunta/(?P<pk>\d+)/$', 'editarPregunta', name='editPregunta'),
    url(r'^/helpers/eliminarpregunta/(?P<pregunta_id>\d+)/$', 'eliminarPregunta', name='eliminarPregunta'),
    url(r'^/helpers/eliminaropcion/(?P<opcion_id>\d+)/$', 'eliminarOpcion', name='eliminarOpcion'),
    url(r'^/crear$', EncuestaCreateView.as_view(), name='crearEncuesta'),
    #url(r'^encuesta/preguntas/(?P<encuesta_id>\d+)/$', 'crearPregunta', name='crearPreguntas'),
    url(r'^/preguntas/(?P<encuesta_id>\d+)/$', EncuestaPreguntaCreateView.as_view(), name='crearPreguntas'),
    url(r'^/ver/(?P<encuesta_id>\d+)/$', VisualizarEncuestaCreateView.as_view(), name='verEncuesta'),
    url(r'^/estadistica/(?P<encuesta_id>\d+)/$', EstadisticaView.as_view(), name='estadisticaEncuesta'),
    url(r'^/estadistica/(?P<encuesta_id>\d+)/pdf/$', EstadisticaViewPdf.as_view(), name='estadisticaPdfEncuesta'),
    #url(r'^/editar/(?P<encuesta_id>\d+)/$', EditarEncuestaView.as_view(), name='editarEncuesta'),
    #url(r'^/editar/(?P<encuesta_id>\d+)/$', EditarEncuestaPreguntaView.as_view(), name='editarPreguntaEncuesta'),
    url(r'^/suspender/(?P<encuesta_id>\d+)/$', 'suspenderEncuesta', name='suspenderEncuesta'),
    url(r'^/eliminar/(?P<encuesta_id>\d+)/$', 'eliminarEncuesta', name='eliminarEncuesta'),
    url(r'^/editar/(?P<encuesta_id>\d+)/$', EditarEncuestaPreguntaViewXeditable.as_view(), name='editarEncuesta'),
    url(r'^/editar/preguntas/(?P<encuesta_id>\d+)/(?P<pregunta_id>\d+)/$', EditarPreguntaView.as_view(), name='editarPregunta'),
    #url(r'^login$', 'iniciar_sesion', name='login'),
    #url(r'^', 'listaEgresados', name='listaEgresados'),
    #url(r'^egresado/addegresado/$', 'addEgresado', name='addEgresado'),
    #url(r'^listaUsuarios/$', UsuariosList.as_view(), name='listaUsuarios'),
    #url(r'^addUsuario$', 'addUsuario', name='addUsuario'),
    #url(r'^listarUsuarios/$', 'listaUsuarios', name='listaUsuarios'),
    
    # url(r'^blog/', include('blog.urls')),


)

oveu/urls.py
from django.conf.urls import patterns, include, url
from apps.usuarios.views import *
from apps.blog.views import *
from apps.eventos.views import *
from apps.oferta.views import *

import settings
#import autocomplete_light
from django.contrib import admin
autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^confirm/(?P<key>\w+)/','apps.usuarios.views.confimar'),
    url(r'^dashboard/egresado/reenviarcodigo/(?P<id_usuario>\d+)/$', 'apps.usuarios.views.reenviarCodigo', name='reenviarCodigo'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^add/(?P<model_name>\w+)/?$', 'tekextensions.views.add_new_model'),
    url(r'^configurar$','apps.usuarios.views.instalar'),
    url(r'^configurar/programas/$','apps.usuarios.views.ProgramaConfFormView' , name='agregarProgramas'),
    url(r'^dashboard/programas/eliminar/(?P<programa_id>\d+)/$','apps.usuarios.views.eliminarPrograma' , name='eliminarPrograma'),
    # url(r'^dashboard/', include('apps.usuarios.urls', namespace='dashurl')),
    #url(r'^agregaregresado', 'apps.usuarios.views.addEgresado', name='Egre'),
    url(r'^dashboard/encuesta', include('apps.encuesta.urls', namespace='encuesta')),
    url(r'^dashboard/informes', include('apps.informes.urls', namespace='informes')),
    url(r'^addE', EgresadoCreateView.as_view()),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    url(r'^panel$', 'apps.usuarios.views.panel', name='panel'),
    url(r'^login$', 'apps.usuarios.views.iniciar_sesion', name='login'),
    url(r'^logout$', 'apps.usuarios.views.logout', name='logout'),
    url(r'^dashboard/egresados$', 'apps.usuarios.views.listaEgresados', name='listaEgresados'),
    url(r'^dashboard/$', 'apps.usuarios.views.dashboard', name='dashboard'),
    url(r'^dashboard/egresadosDesactualizados$', 'apps.usuarios.views.listaEgresadosDesactualizados', name='listaEgresadosDesactualizados'),
    url(r'^dashboard/usuarios/$', 'apps.usuarios.views.usuarios', name='usuarios'),
    #urls para empresas
    url(r'^dashboard/empresas/$', 'apps.usuarios.views.listaEmpresas', name='listaEmpresas'),
    url(r'^dashboard/empresa/(?P<empresa_id>\d+)/$', 'apps.usuarios.views.toggleEmpresa', name='toggleEmpresa'),
    url(r'^dashboard/addEmpresa/$', 'apps.usuarios.views.addEmpresa', name='addEmpresa'),
    #fin urls empresas
    #urls para eventos
    url(r'^dashboard/eventos', include('apps.eventos.urls',namespace='eventos')), 
    #url(r'^dashboard/eventos/$', 'apps.eventos.views.listaEventos', name='listaEventos'),
    #url(r'^dashboard/evento/add$', 'apps.eventos.views.addEvento', name='addEvento'),
    #url(r'^dashboard/evento/edit/(?P<evento_id>\d+)/$', 'apps.eventos.views.editEvento', name='editEvento'),
    #url(r'^dashboard/evento/detail/(?P<evento_id>\d+)/$', 'apps.eventos.views.detalleEvento', name='detailEvento'),
    #fin urls eventos
    url(r'^dashboard/addCoordinador$', 'apps.usuarios.views.addCoordinador', name='addCoordinador'),
    url(r'^dashboard/actualizarCoordinador$', CoordinadorUpdateView.as_view(), name='actualizarCoordinador'),
    
    url(r'^dashboard/egresado/addEgresado/$', EgresadoCreateView.as_view(), name='addEgresado'),
    url(r'^dashboard/egresado/edit/(?P<pk>\d+)/$', EgresadoUpdateView.as_view(), name='editEgresado'),
    url(r'^dashboard/egresado/eliminar/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.eliminarEgresado', name='eliminarEgresado'),
    url(r'^admin/', include(admin.site.urls)),
    #urls de blogs
    url(r'^', include('apps.blog.urls')),
    #dashboard portal web
    url(r'^dashboard/portal/addEntrada/$', 'apps.blog.views.addEntrada', name='addEntrada'),
    url(r'^dashboard/portal/editEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.editEntrada', name='editEntrada'),
    url(r'^dashboard/portal/delEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.delEntrada', name='delEntrada'),
    url(r'^dashboard/portal/addCategoria/$', 'apps.blog.views.addCategoria', name='addCategoria'),
    url(r'^dashboard/portal/listaCategoria/$', 'apps.blog.views.listaCategoria', name='listaCategoria'),
    url(r'^dashboard/portal/listaCategoria/edit/(?P<categorias_id>\d+)/$', 'apps.blog.views.editCategoria', name='editCategoria'),
    url(r'^dashboard/portal/listaCategoria/del/(?P<categorias_id>\d+)/$', 'apps.blog.views.delCategoria', name='delCategoria'),
    url(r'^dashboard/portal/listaEntrada/$', 'apps.blog.views.listaEntrada', name='listaEntrada'),

    #urls de oferta laboral
    url(r'^dashboard/oferta', include('apps.oferta.urls')),
    #urls de correo
    url(r'^dashboard/correo', include('apps.correo.urls', namespace='correo')),  
    #urls de tinycme 
    url(r'^tinymce/', include('tinymce.urls')),
    #url programas
    url(r'^dashboard/programas/addPrograma$', ProgramaFormView.as_view(), name='addPrograma'),
    url(r'^dashboard/programas/list/$', ProgramaListView.as_view(), name='listaProgramas'),
    url(r'^dashboard/programas/edit/(?P<pk>\d+)/$', 'apps.usuarios.views.ProgramaUpdate', name='updatePrograma'),
    #fin url
    url(r'^dashboard/helper/busquedaAjax/', 'apps.usuarios.views.busquedaAjax', name='busquedaAjax'),
    url(r'^dashboard/egresado/detail/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.detailEgresado', name='detailEgresado'),
)

apps/encuesta/models.py
from django.db import models
from apps.usuarios.models import Administrador, Usuario

TIPO_ENCUESTA = (
	('egresado', 'Egresados'),
	('empresa', 'Empresas'),
	('todos', 'Todos (egresados y empresas)')
)

class Encuesta(models.Model):


	titulo = models.CharField(max_length=100)
	descripcion = models.TextField()
	estado = models.BooleanField(default=False, verbose_name='Publicada?')
	imagen = models.ImageField(upload_to="img_encuesta", null=True, blank=True)
	tipo = models.CharField(max_length=15, choices=TIPO_ENCUESTA, default='egresado')
	administrador = models.ForeignKey(Administrador)
	enviado = models.BooleanField(default=False,)

	def __unicode__(self):
		return "%s" % self.titulo

	def realizadas(self):
		respuesta =  Respuesta.objects.filter(encuesta=self).values_list('usuario', flat=True).distinct().count()
		respuestav = RespuestaV.objects.filter(encuesta=self).values_list('usuario', flat=True).distinct().count()
		
		if respuesta == 0:
			if respuestav > 0:
				realizada = respuestav
			else:
				realizada = respuestav
		else:
			realizada = respuesta

		return realizada


TIPO_PREGUNTA = (
	('UN', 'Unica Respuesta'),
	('MU', 'Multiple Respuesta'),
	('AB', 'Desarrollo'),
)


class Pregunta(models.Model):

	pregunta = models.CharField(max_length=50)
	tipo = models.CharField(max_length=2, choices=TIPO_PREGUNTA)
	opcional = models.BooleanField(default=False)
	encuesta = models.ForeignKey(Encuesta)

	def __unicode__(self):
		return "%s" % self.pregunta
    
class Opcion(models.Model):


	opcion = models.CharField(max_length=70)
	pregunta = models.ForeignKey(Pregunta)
	
	def __unicode__(self):
		return self.opcion

class Respuesta(models.Model):


	fecha_creacion = models.DateTimeField(auto_now=True, auto_now_add=True)
	pregunta = models.ForeignKey(Pregunta)
	usuario = models.ForeignKey(Usuario)
	opcion = models.ForeignKey(Opcion)
	encuesta = models.ForeignKey(Encuesta)


class RespuestaV(models.Model):


	respuesta = models.TextField()
	pregunta = models.ForeignKey(Pregunta)
	usuario = models.ForeignKey(Usuario)
	encuesta = models.ForeignKey(Encuesta)

	def __unicode__(self):
		return self.respuesta
    

apps/eventos/models.py
from django.db import models
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
from apps.usuarios.models import Administrador, Egresado
import datetime

class Evento(models.Model):
	titulo = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_inicio = models.DateTimeField()
	fecha_fin = models.DateTimeField()
	imagen = models.ImageField(upload_to='img_evento', blank=True, null=True)
	telefono = models.CharField(max_length=20)
	correo = models.EmailField()
	direccion = models.CharField(max_length=120)
	estado = models.BooleanField(default=False, verbose_name='Publicado')
	coordinador = models.ForeignKey(Administrador)
	fecha_creacion = models.DateTimeField(auto_now=True,auto_now_add=True, default=datetime.datetime.now())
	enviado = models.BooleanField(default=False, verbose_name='Correo enviado?')

	def __unicode__(self):
		return self.titulo

# borrar imagen del disco duro
@receiver(pre_delete, sender=Evento)
def post_pre_delete_handler(sender, instance, **kwargs):
	instance.imagen.delete(False)


class Asistente(models.Model):
	"""docstring for Asistente"""
	egresado = models.ForeignKey(Egresado)
	evento = models.ForeignKey(Evento)
	

apps/encuesta/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import *
from django.forms.models import BaseInlineFormSet

#validacion para que el primero de los inline formset sea requerido
class CustomInlineFormSet(BaseInlineFormSet):
	def clean(self):
        # get forms that actually have valid data
		count = 0
		for form in self.forms:
			try:
				if form.cleaned_data:
					count += 1
			except AttributeError:
				# annoyingly, if a subform is invalid Django explicity raises
				# an AttributeError for cleaned_data
				pass
		if count < 1:
			raise forms.ValidationError('You must have at least one order')

class EncuestaUpdateForm(forms.ModelForm):
	class Meta:
		model = Encuesta
		exclude = ['administrador', 'estado', 'enviado', 'tipo']

class EncuestaCreateForm(forms.ModelForm):
	class Meta:
		model = Encuesta
		exclude = ['administrador', 'estado', 'enviado']

class PreguntaForm(forms.ModelForm):
    class Meta:
        model = Pregunta
        exclude = ['encuesta',]

class OpcionForm(forms.ModelForm):
    class Meta:
        model = Opcion
        exclude = ['pregunta',]

OpcionFormSet = inlineformset_factory(Pregunta, Opcion, form=OpcionForm, can_delete=True, extra=0)

oveu/templates/encuesta/editar_pregunta_encuesta.html
{% extends "usuarios/basePanel.html" %}
{% load staticfiles %}
{% load formset_tags %}
{% load widget_tweaks %}

{% load bootstrap3 %}
{% block estaticos %}
<link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>

{% endblock%}
{% block user %}
  {% include "usuarios/user-info.html" %}
{% endblock %}
{% block contenido_panel %}

    <div class="row" style="width:80%;margin:0 auto;">
        <div class="col-sm-8">

            {% if encuesta.estado %}
                <div class="alert alert-info" style="margin:10px">
                        
                        La encuesta esta publicada, para poder hacer modificaciones es necesario suspenderla.
                    </div> 

                    <br>
                    <a href="{% url 'encuesta:suspenderEncuesta' encuesta.id %}" class="btn btn-primary">Suspender</a>   
            {% else %}

            <form class="form" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                <h2 style="color:#c33833;font-weight:bold;padding-bottom: 10px;">Editar encuesta</h2>
                <fieldset>
                    <legend>Datos de la encuesta</legend>
                     {% bootstrap_form form %}
                </fieldset>
                <br>
                <fieldset>
                    <legend>Preguntas</legend>
                    

                {% for pregunta in preguntas  %}
                <div id="pregunta{{pregunta.id}}">
                                 
                    <h4>  <a href="#" class="pregunta-edit" id="pregunta" data-type="text" data-pk="{{pregunta.pk}}" data-title="Enter username" data-url="{% url 'encuesta:editPregunta' pregunta.pk %}" title="Editar la pregunta" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ pregunta.pregunta }}</a> <span onclick="eliminarPregunta({{pregunta.id}})" style="color:#c33833;cursor:pointer;" data-toggle="tooltip" data-placement="right" title="Eliminar la pregunta"><i class="fa fa-times"></i></span> </h4>
                        <ul id="opciones">
                            
                        {% for key, op in opciones.items  %}
                            
                            {% if key == pregunta.pk %}
                            {% for o in op  %}
                           
                             <li id="opcion{{o.0}}" style="margin: 3px 0"><a href="#" id="username" data-type="text" data-pk="{{o.0}}" data-title="Enter username" data-url="{% url 'encuesta:editOpcion' o.0%}" title="Editar la opcion" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{o.1}}</a> <span onclick="eliminarOpcion({{o.0}})" style="color:#c33833;border:none;cursor:pointer;" title="Eliminar la opcion"><i class="fa fa-times"></i></span></li>   
                            {% empty %}
                            <li>Pregunta abierta</li>
                            {% endfor %}
                                
                            
                            {% endif %}
                        {% endfor %} 
                        <br>
                        
                        </ul>
                        </div>
                        {% empty %}
                    No tiene preguntas, <a href="{% url 'encuesta:crearPreguntas' encuesta.id %}" class="btn btn-success btn-sm"> Agregar preguntas</a>
                {% endfor %}   

            {% if preguntas|length > 0 %}
                
               <a href="{% url 'encuesta:crearPreguntas' encuesta.id %}" class="btn btn-success btn-sm"> Agregar nuevas preguntas</a>
            {% endif %}
                </fieldset>
                
                <hr />
                <div class="form-group">
                    <div class="col-sm-offset-2 col-lg-6 col-sm-10">
                        <input type="submit" class="btn btn-primary" value="Actualizar" />
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </div>

{% endblock %}
{% block js %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $.fn.editable.defaults.mode = 'inline';
        $('#opciones li a').editable({validate: function(value) {
            if($.trim(value) == '') {
                return 'No puedes dejar el campo vacio';
            }}
        });
        $('.pregunta-edit').editable({validate: function(value) {
            if($.trim(value) == '') {
                return 'No puedes dejar el campo vacio';
            }}
        });
        

    });
</script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script src="{% static '/static/js/jquery.ui.datepicker-es.js' %}"></script>
<script src="{% static  '/static/css/jquery-ui-1.10.4.custom.min.css'%}"></script>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

    function eliminarPregunta(id) {

        var r = confirm("Quieres eliminar la pregunta?");
        if (r == true) {
            $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $.ajax({
              url: 'http://localhost:8000/dashboard/encuesta/helpers/eliminarpregunta/'+id+'/',
              type: 'POST',
              success: function(data) {
                $('#pregunta'+id).remove();
                console.log('se elimino');
              },
              error: function(data) {
                  console.log('no se pudo eliminar');
              }
            });
        } else {
            alert('No');
        }
        
    };

    function eliminarOpcion(id) {

        var r = confirm("Quieres eliminar la opcion?");
        if (r == true) {
            $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $.ajax({
              url: 'http://localhost:8000/dashboard/encuesta/helpers/eliminaropcion/'+id+'/',
              type: 'POST',
              success: function(data) {
                $('#opcion'+id).remove();
                console.log('se elimino');
              },
              error: function(jqXHR,textStatus, errorThrown) {
                  console.log(jqXHR.status, textStatus, errorThrown);
              }
            });
        } else {
            alert('No');
        }
        
    };
    function popup(url,ancho,alto) {
        var posicion_x; 
        var posicion_y; 
        posicion_x=(screen.width/2)-(ancho/2); 
        posicion_y=(screen.height/2)-(alto/2); 
        window.open(url, "width="+ancho+",height="+alto+",menubar=0,toolbar=0,directories=0,scrollbars=no,resizable=no,left="+posicion_x+",top="+posicion_y+"");
    }
            
        $("#id_fecha_cumple").datepicker({
            firstDay: 1,
            changeMonth: true,
            changeYear: true,
            yearRange: "c-30:c+3"
        });

        $("#id_fecha_grado").datepicker({
            firstDay: 1,
            changeMonth: true,
            changeYear: true,
            yearRange: "c-30:c+3"
        });
        $(".fecha").datepicker({
            firstDay: 1,
            changeMonth: true,
            changeYear: true,
            yearRange: "c-30:c+3"
        });

    
</script>




{% endblock %}

oveu/templates/encuesta/encuesta_list.html
{% extends "usuarios/basePanel.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% block user %}
	{% include "usuarios/user-info.html" %}
{% endblock %}
{% block estaticos  %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.css">
{% endblock %}

{% block contenido_panel %}
	
					<div style="margin:0 1% 40px 1%;border-radius: 6px;background:#f2f2f2;overflow:hidden;padding:10px">	

						<a href="#" id="clickSearch" style="font-size:23px; color:#c33833;margin-left: 10px;text-decoration:none;"><i class="fa fa-search"></i> Buscar</a>
				<!--<h4 style="color:#c33833;font-weight:bold">Busqueda</h4>-->
			<!--<form method="POST">
			<div class="form-inline">
				{% csrf_token %}
				<div class="form-group">
					<input type="text" id="text" class="form-control" placeholder="Busqueda" name="query" required>    
				</div>
				<div class="form-group">
					<select name="busqueda" class="form-control">
							<option value="titulo" selected>Titulo</option>
							<option value="descripcion">Descripcion</option>
					</select>
				</div>
				
				<div class="form-group" style="margin-left:5px">
					<input type="submit" class="btn btn-primary" value="Buscar">
				</div>
			</div>
			</form>-->
				<div  style="float:right;margin-right:15px">
					<a href="{% url 'encuesta:crearEncuesta' %}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Crear Encuesta</a>
				</div>
		</div>

		<div id="busqueda" style="width:50%;margin: 10px 40px; display:none;font-size:10px;">
			<h2 class="titulos">Busqueda</h2>
			<form action="" method="get">
        {{ filter.form|bootstrap }}
        <input type="submit" class="btn btn-primary"/>
    </form>
    <br>
    <br>

</div>	
	<div style="width:90%; margin:0 auto">

		<h2 class="titulos">Lista de Encuesta</h2>
		<table class="table table-hover tablesorter" id="myTable">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Descripcion</th>
					<th>#Realizadas</th>
					<th>Publicada?</th>
					<th>Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for encuesta in filter %}
				<tr>
						<th style="width:29%">{{ encuesta.titulo }}</th>
						<th style="width:20%">{{ encuesta.descripcion|truncatechars:100 }}</th>
						<th> {{ encuesta.realizadas }}</th>
						{% if encuesta.estado == True %}
							<th><i class="fa fa-check"></i></th>
						{% else %}
							<th><i class="fa fa-ban"></i></th>
						{% endif %}
						<th><a class="btn btn-info btn-sm" href="{% url 'encuesta:editarEncuesta' encuesta.id %}"><i class="fa fa-pencil"></i> Editar</a> <a class="btn btn-info btn-sm" href="{% url 'encuesta:verEncuesta' encuesta.pk %}"><i class="fa fa-eye"></i> Ver</a> <a class="btn btn-info btn-sm" href="{% url 'encuesta:estadisticaEncuesta' encuesta.pk %}"><i class="fa fa-area-chart"></i></a>
							<a class="btn btn-danger btn-sm confirmation"  href="{% url 'encuesta:eliminarEncuesta' encuesta.pk %}"><i class="fa fa-times"></i></a></th>
						
					</tr>
				{% empty %}
					<tr>
					<th>No hay encuestas para mostrar</th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
				
				{% endfor %}
			</tbody>
		</table>
			 
		</div>
	
{% endblock %}

{% block js%}
	<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/a5734b29083/integration/bootstrap/3/dataTables.bootstrap.js"></script>

<script src="{% static  '/static/js/bootstrap-confirmation.js'%}"></script>
	<script>
		$(document).ready(function() 
	    { 
	    	$('#myTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/a5734b29083/i18n/Spanish.json"
            }
        });
	        $("#myTable").tablesorter({sortList: [[0,0]],headers:{ 4: { sorter: false},5: { sorter: false}}}); 
	    });
		
		$(document).ready(function() 
	    { 
	    	$("#clickSearch").click(function() {
	    		$("#busqueda").toggle('slow');
	    });


	    
	    
    	$('.confirmation').confirmation({'title':"Si eliminas esta encuesta, se borrara tambien sus preguntas y sus respuestas.", 'placement':"top", 'singleton':true, 'popout':true, 'btnOkLabel':"Eliminar", 'btnCancelLabel':"Cancelar"});


	    });


	</script>


{% endblock %}