apps/informes/urls.py
from django.conf.urls import patterns, url
from apps.informes.views import *
from wkhtmltopdf.views import PDFTemplateView



urlpatterns = patterns('apps.informes.views',
    # Examples:
    url(r'^/$', IndexInformeView.as_view(), name='indexInformes'),
    #url(r'^/pdf/$', MyPDF.as_view(), name='pdf'),
    url(r'^/graficos/$', Graficos.as_view(), name='graficos'),
    url(r'^/chrome/$', HomePageView.as_view(), name='cr'),
    url(r'^/grafico/(?P<numero>\d+)/$', GraficoDetalle.as_view(), name='graficoDetalle'),
    url(r'^/graficos/primergraficopdf/$', 'PrimerInformePdf', name='primerGrafico'),
    url(r'^/graficos/segundograficopdf/$', 'SegundoInformePdf', name='segundoGrafico'),
    url(r'^/graficos/tercerograficopdf/$', 'TerceroInformePdf', name='terceroGrafico'),
    url(r'^/graficos/cuartograficopdf/$', 'CuartoInformePdf', name='cuartoGrafico'),
    url(r'^/graficos/quintograficopdf/$', 'QuintoInformePdf', name='quintoGrafico'),
    url(r'^/graficos/sextograficopdf/$', 'SextoInformePdf', name='sextoGrafico'),
    url(r'^/graficos/septimograficopdf/$', 'SeptimoInformePdf', name='septimoGrafico'),
    url(r'^/graficos/octavograficopdf/$', 'OctavoInformePdf', name='octavoGrafico'),
    url(r'^/graficos/novenograficopdf/$', 'NovenoInformePdf', name='novenoGrafico'),
    url(r'^/graficos/decimograficopdf/$', 'DecimoInformePdf', name='decimoGrafico'),
    url(r'^/graficos/Undecimograficopdf/$', 'UnDecimoInformePdf', name='undecimoGrafico'),
    url(r'^/graficos/docegraficopdf/$', 'DoceInformePdf', name='doceGrafico'),
    url(r'^/graficos/trecegraficopdf/$', 'TreceInformePdf', name='treceGrafico'),
    url(r'^/graficos/catorcegraficopdf/$', 'CatorceInformePdf', name='catorceGrafico'),
    url(r'^/graficos/quincegraficopdf/$', 'QuinceInformePdf', name='quinceGrafico'),
    url(r'^/graficos/dieciseisgraficopdf/$', 'DieciseisInformePdf', name='dieciseisGrafico'),
    url(r'^/graficos/diecisietegraficopdf/$', 'DiecisieteInformePdf', name='diecisieteGrafico'),
    url(r'^/graficos/dieciochograficopdf/$', 'DieciochoInformePdf', name='dieciochoGrafico'),
    url(r'^/graficos/diecinuevegraficopdf/$', 'DiecinueveInformePdf', name='diecinueveGrafico'),
    #url(r'^encuesta/crear$', EncuestaCreateView.as_view(), name='crearEncuesta'),
    # url(r'^blog/', include('blog.urls')),


)

oveu/urls.py
from django.conf.urls import patterns, include, url
from apps.usuarios.views import *
from apps.blog.views import *
from apps.eventos.views import *
from apps.oferta.views import *

import settings
#import autocomplete_light
from django.contrib import admin
autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^confirm/(?P<key>\w+)/','apps.usuarios.views.confimar'),
    url(r'^dashboard/egresado/reenviarcodigo/(?P<id_usuario>\d+)/$', 'apps.usuarios.views.reenviarCodigo', name='reenviarCodigo'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^add/(?P<model_name>\w+)/?$', 'tekextensions.views.add_new_model'),
    url(r'^configurar$','apps.usuarios.views.instalar'),
    url(r'^configurar/programas/$','apps.usuarios.views.ProgramaConfFormView' , name='agregarProgramas'),
    url(r'^dashboard/programas/eliminar/(?P<programa_id>\d+)/$','apps.usuarios.views.eliminarPrograma' , name='eliminarPrograma'),
    # url(r'^dashboard/', include('apps.usuarios.urls', namespace='dashurl')),
    #url(r'^agregaregresado', 'apps.usuarios.views.addEgresado', name='Egre'),
    url(r'^dashboard/encuesta', include('apps.encuesta.urls', namespace='encuesta')),
    url(r'^dashboard/informes', include('apps.informes.urls', namespace='informes')),
    url(r'^addE', EgresadoCreateView.as_view()),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    url(r'^panel$', 'apps.usuarios.views.panel', name='panel'),
    url(r'^login$', 'apps.usuarios.views.iniciar_sesion', name='login'),
    url(r'^logout$', 'apps.usuarios.views.logout', name='logout'),
    url(r'^dashboard/egresados$', 'apps.usuarios.views.listaEgresados', name='listaEgresados'),
    url(r'^dashboard/$', 'apps.usuarios.views.dashboard', name='dashboard'),
    url(r'^dashboard/egresadosDesactualizados$', 'apps.usuarios.views.listaEgresadosDesactualizados', name='listaEgresadosDesactualizados'),
    url(r'^dashboard/usuarios/$', 'apps.usuarios.views.usuarios', name='usuarios'),
    #urls para empresas
    url(r'^dashboard/empresas/$', 'apps.usuarios.views.listaEmpresas', name='listaEmpresas'),
    url(r'^dashboard/empresa/(?P<empresa_id>\d+)/$', 'apps.usuarios.views.toggleEmpresa', name='toggleEmpresa'),
    url(r'^dashboard/addEmpresa/$', 'apps.usuarios.views.addEmpresa', name='addEmpresa'),
    #fin urls empresas
    #urls para eventos
    url(r'^dashboard/eventos', include('apps.eventos.urls',namespace='eventos')), 
    #url(r'^dashboard/eventos/$', 'apps.eventos.views.listaEventos', name='listaEventos'),
    #url(r'^dashboard/evento/add$', 'apps.eventos.views.addEvento', name='addEvento'),
    #url(r'^dashboard/evento/edit/(?P<evento_id>\d+)/$', 'apps.eventos.views.editEvento', name='editEvento'),
    #url(r'^dashboard/evento/detail/(?P<evento_id>\d+)/$', 'apps.eventos.views.detalleEvento', name='detailEvento'),
    #fin urls eventos
    url(r'^dashboard/addCoordinador$', 'apps.usuarios.views.addCoordinador', name='addCoordinador'),
    url(r'^dashboard/actualizarCoordinador$', CoordinadorUpdateView.as_view(), name='actualizarCoordinador'),
    
    url(r'^dashboard/egresado/addEgresado/$', EgresadoCreateView.as_view(), name='addEgresado'),
    url(r'^dashboard/egresado/edit/(?P<pk>\d+)/$', EgresadoUpdateView.as_view(), name='editEgresado'),
    url(r'^dashboard/egresado/eliminar/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.eliminarEgresado', name='eliminarEgresado'),
    url(r'^admin/', include(admin.site.urls)),
    #urls de blogs
    url(r'^', include('apps.blog.urls')),
    #dashboard portal web
    url(r'^dashboard/portal/addEntrada/$', 'apps.blog.views.addEntrada', name='addEntrada'),
    url(r'^dashboard/portal/editEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.editEntrada', name='editEntrada'),
    url(r'^dashboard/portal/delEntrada/(?P<entradas_id>\d+)/$', 'apps.blog.views.delEntrada', name='delEntrada'),
    url(r'^dashboard/portal/addCategoria/$', 'apps.blog.views.addCategoria', name='addCategoria'),
    url(r'^dashboard/portal/listaCategoria/$', 'apps.blog.views.listaCategoria', name='listaCategoria'),
    url(r'^dashboard/portal/listaCategoria/edit/(?P<categorias_id>\d+)/$', 'apps.blog.views.editCategoria', name='editCategoria'),
    url(r'^dashboard/portal/listaCategoria/del/(?P<categorias_id>\d+)/$', 'apps.blog.views.delCategoria', name='delCategoria'),
    url(r'^dashboard/portal/listaEntrada/$', 'apps.blog.views.listaEntrada', name='listaEntrada'),

    #urls de oferta laboral
    url(r'^dashboard/oferta', include('apps.oferta.urls')),
    #urls de correo
    url(r'^dashboard/correo', include('apps.correo.urls', namespace='correo')),  
    #urls de tinycme 
    url(r'^tinymce/', include('tinymce.urls')),
    #url programas
    url(r'^dashboard/programas/addPrograma$', ProgramaFormView.as_view(), name='addPrograma'),
    url(r'^dashboard/programas/list/$', ProgramaListView.as_view(), name='listaProgramas'),
    url(r'^dashboard/programas/edit/(?P<pk>\d+)/$', 'apps.usuarios.views.ProgramaUpdate', name='updatePrograma'),
    #fin url
    url(r'^dashboard/helper/busquedaAjax/', 'apps.usuarios.views.busquedaAjax', name='busquedaAjax'),
    url(r'^dashboard/egresado/detail/(?P<egresado_id>\d+)/$', 'apps.usuarios.views.detailEgresado', name='detailEgresado'),
)

apps/informes/models.py
from django.db import models

# Create your models here.

apps/informes/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.base import View
from wkhtmltopdf.views import PDFTemplateView
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from cities_light.models import City, Country
from apps.usuarios.models import Egresado, DireccionActual, EstudiosRealizados, Idioma, Asociacion, Premio, Programa
import datetime
from wkhtmltopdf.views import PDFTemplateResponse
from django.db.models import Q
from django.http import Http404
#import requests


class HomePageView(TemplateView):
    template_name = "informes/pdfc.html"

def PrimerInformePdf(request):
	c = DireccionActual.objects.values_list('ciudad', flat=True).distinct()
	data = []
	nombre_pdf = 'PrimerInformePdf-%s.pdf' % (datetime.datetime.now())
	date_generated = datetime.datetime.now()
	for da in c:
		#d contiene la cantidad de inserciones que tienen la ciudad da[]
		
		city = City.objects.get(pk=da)
		
		cantidad = DireccionActual.objects.filter(ciudad=da).count()
		nombre = city.name.encode('utf8')
		fila = [nombre, cantidad]
		data.append(fila)

	return PDFTemplateResponse(request=request,
									template="informes/1pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {'margin-top':25,'margin-bottom':20}
									)

def SegundoInformePdf(request):
	nombre_pdf = 'SegundoInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = 0
	no = 0
	for e in egresados:
		estudio = EstudiosRealizados.objects.filter(egresado=e).filter(tipo="especializacion").first()
		if estudio:
			si+=1
		else:
			no+=1
	sil = ["Si", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)

	return PDFTemplateResponse(request=request,
									template="informes/2pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)
def TerceroInformePdf(request):
	nombre_pdf = 'TerceroInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = egresados.filter(estado_laboral='laborando en su profesion').count()
	no = egresados.count() - si

	print si
	print no
	sil = ["Si", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)

	return PDFTemplateResponse(request=request,
									template="informes/3pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)
def CuartoInformePdf(request):
	nombre_pdf = 'CuartoInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = egresados.filter(estado_laboral='laborando en su profesion').count()
	no = egresados.count() - si

	print si
	print no
	sil = ["Si", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)

	return PDFTemplateResponse(request=request,
									template="informes/4pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)


def QuintoInformePdf(request):
	nombre_pdf = 'QuintoInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = 0
	no = 0
	for e in egresados:
		if e.estado == "fallecido":
			si+=1
		else:
			no+=1

	sil = ["Fallecidos", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)
	return PDFTemplateResponse(request=request,
									template="informes/5pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)

def SextoInformePdf(request):
	nombre_pdf = 'SextoInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = 0
	no = 0
	for e in egresados:
		estudio = EstudiosRealizados.objects.filter(egresado=e).filter(tipo="magister").first()
		if estudio:
			si+=1
		else:
			no+=1
	sil = ["Si", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)
	return PDFTemplateResponse(request=request,
									template="informes/6pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)

def SeptimoInformePdf(request):
	nombre_pdf = 'SeptimoInformePdf-%s.pdf' % (datetime.datetime.now())
	escuelas = Programa.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	for e in escuelas:
		egresados = Egresado.objects.filter(programa=e)
		cantidadEgresado = egresados.count()
		desactualizados = egresados.filter(ultima_modificacion__lte=datetime.datetime.now() - datetime.timedelta(days=180)).exclude(estado='fallecido').count()
		actualizados = cantidadEgresado - desactualizados
		lista = [e.nombre,actualizados, desactualizados]
		data.append(lista)
	return PDFTemplateResponse(request=request,
									template="informes/7pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)

def OctavoInformePdf(request):
	nombre_pdf = 'OctavoInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = egresados.filter(Q(estado_laboral='laborando en su profesion') | Q(estado_laboral='Laborando fuera de su profesion') | Q(estado_laboral='Laborando y estudiando')).count()
	print si
	no = egresados.count() - si
	sil = ["Si", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)
	return PDFTemplateResponse(request=request,
									template="informes/8pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)

def NovenoInformePdf(request):
	nombre_pdf = 'NovenoInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = egresados.filter(estado_laboral='Desempleado').count()
	no = egresados.count() - si
	sil = ["Si", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)
	return PDFTemplateResponse(request=request,
									template="informes/9pdf.html",
									context={"data": data, "tiempo":date_generated},
									filename=nombre_pdf,
									header_template="informes/header.html",
									footer_template="informes/footer.html",
									show_content_in_browser=True,
									cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
									)


def DecimoInformePdf(request):
	nombre_pdf = 'DecimoInformePdf-%s.pdf' % (datetime.datetime.now())
	egresados = Egresado.objects.all()
	date_generated = datetime.datetime.now()
	data = []
	si = Egresado.objects.filter(Q(estado_laboral='Laborando y estudiando') | Q(estado_laboral='Estudiando')).count()
	print si
	no = egresados.count() - si
	sil = ["Si", si ]
	nol = ["No", no ]
	data.append(sil)
	data.append(nol)
	return PDFTemplateResponse(request=request,
								template="informes/10pdf.html",
								context={"data": data, "tiempo":date_generated},
								filename=nombre_pdf,
								show_content_in_browser=True, 
								header_template='informes/header.html',
								footer_template="informes/footer.html",
								cmd_options = {
										'margin-top': 25,
										'margin-bottom':20
									}
								)

def UnDecimoInformePdf(request):
	
	c = DireccionActual.objects.all().exclude(ciudad__country__pk=49)
	data = []
	nombre_pdf = 'UnDecimoInformePdf-%s.pdf' % (datetime.datetime.now())
	date_generated = datetime.datetime.now()	
	data = []
	
	for da in c:
		#d contiene la cantidad de inserciones que tienen la ciudad da[]
		
		country = Country.objects.get(pk=da.ciudad.country.pk)
			
		cantidad = DireccionActual.objects.filter(ciudad__country=country).count()
		nombre = country.name.encode('utf8')
		fila = [nombre, cantidad]
		if not fila in data:
			data.append(fila)

	return PDFTemplateResponse(request=request,
								template="informes/11pdf.html",
								context={"data": data, "tiempo": date_generated},
								filename=nombre_pdf,
								show_content_in_browser=True, 
								header_template='informes/header.html',
								footer_template="informes/footer.html",
								cmd_options = {

oveu/templates/informes/11.html
{% extends "usuarios/basePanel.html" %}
{% load bootstrap %}
{% block user %}
    {% include "usuarios/user-info.html" %}
{% endblock %}
{% block estaticos %}

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
{% if data|length > 0 %}
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        
          var data = google.visualization.arrayToDataTable([
            ['Ciudades', 'Cantidad'],
            {% for d in data %}
              ["{{ d.0 }}", {{d.1}}],
            {% empty %}
              ["ninguna", 0],
            {% endfor %}

            ]);


        var options = {
            hAxis: {title: 'Ciudades', titleTextStyle: {color: 'red'}},
        };

        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        // Wait for the chart to finish drawing before calling the getImageURI() method.
        google.visualization.events.addListener(chart, 'ready', function () {
          
        document.getElementById('imagen').outerHTML = '<a href="' + chart.getImageURI() + '" target="_blank">Imagen de Grafico</a>';
        });
        

        chart.draw(data, options);
      }

    </script>
{% endif %}
{% endblock %}

{% block contenido_panel %}

<div style="margin:0 1% 10px 1%;border-radius: 6px;background:#f2f2f2;overflow:hidden;padding:10px">  
        <!--<h4 style="color:#c33833;font-weight:bold">Busqueda</h4>-->
        <form method="POST" action="{% url 'informes:graficos' %}">
          {% csrf_token %}
      <div class="form-inline">
        <div class="form-group">
          {% include 'informes/informesList.html'%}
        </div>
                
        <div class="form-group" style="float:right;margin-right:15px">
          <input type="submit" class="btn btn-success" value="Ir">  
        </div>
      </div>
      </form>
    </div>

	<div class="row" style="width:80%;margin:8px auto;">
      <div class="col-8">
          <h2 class="titulos">Cantidad de Egresados en el exterior</h2>
            {% if data|length > 0 %}
              <div>
                <a href="{% url 'informes:undecimoGrafico' %}" class="btn btn-default"><i class="fa fa-file-pdf-o"></i> Generar PDF </a>
              </div>
              
              <div id="chart_div" style="width: 900px; height: 500px;"></div>
              <div id='imagen'></div>
              <br>
              <table class="table table-hover">
              <thead><tr><th>Ciudad</th><th>#Cantidad</th></tr>
              </thead>
            <tbody>
              {% for d in data  %}
                
                <tr> <td>{{ d.0 }}</td><td>{{ d.1 }}</td></tr>
                
              {% endfor %}
            </tbody>
          </table>
            {% else %}
              <span>No hay datos para realizar el grafico</span>
            {% endif %}
      </div>
  </div>
{% endblock %}

oveu/templates/informes/15.html
{% extends "usuarios/basePanel.html" %}
{% load bootstrap %}
{% block user %}
    {% include "usuarios/user-info.html" %}
{% endblock %}
{% block estaticos %}

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        
          var data = google.visualization.arrayToDataTable([
            ['Element', 'Cantidad'],
            {% for d in data %}
              ["{{ d.0 }}", {{d.1}}],
            {% endfor %}
            ]);


        var options = {
            pieHole: 0.4,
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        
        // Wait for the chart to finish drawing before calling the getImageURI() method.
        google.visualization.events.addListener(chart, 'ready', function () {
          
        document.getElementById('imagen').outerHTML = '<a href="' + chart.getImageURI() + '" target="_blank">Imagen de Grafico</a>';
        });

        chart.draw(data, options);
      }
    </script>

{% endblock %}

{% block contenido_panel %}

<div style="margin:0 1% 10px 1%;border-radius: 6px;background:#f2f2f2;overflow:hidden;padding:10px">  
        <!--<h4 style="color:#c33833;font-weight:bold">Busqueda</h4>-->
        <form method="POST" action="{% url 'informes:graficos' %}">
          {% csrf_token %}
      <div class="form-inline">
        
        <div class="form-group">
          {% include 'informes/informesList.html'%}
        </div>
                
        <div class="form-group" style="float:right;margin-right:15px">
          <input type="submit" class="btn btn-success" value="Ir">  
        </div>
      </div>
      </form>
    </div>

  <div class="row" style="width:80%;margin:8px auto;">
      <div class="col-8">
          <h2 class="titulos">Egresados que han recibido premios</h2>
          {% if data|length > 0 %}

              <div>
                <a href="{% url 'informes:quinceGrafico' %}" class="btn btn-default"> <i class="fa fa-file-pdf-o"></i> Generar PDF </a>
              </div>
              <div id="chart_div" style="width: 900px; height: 500px;"></div>
              <div id='imagen'></div>
              <br>
              <table class="table table-hover">
              <thead><tr><th>Opcion</th><th>#Cantidad</th></tr>
              </thead>
            <tbody>
              {% for d in data  %}
                
                <tr> <td>{{ d.0 }}</td><td>{{ d.1 }}</td></tr>
                
              {% endfor %}
            </tbody>
          </table>
          {% else %}
              <span>No hay datos para realizar el grafico</span>
            {% endif %}
      </div>
  </div>
{% endblock %}

oveu/templates/informes/17.html
{% extends "usuarios/basePanel.html" %}
{% load bootstrap %}
{% block user %}
    {% include "usuarios/user-info.html" %}
{% endblock %}
{% block estaticos %}

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        
          var data = google.visualization.arrayToDataTable([
            ['Element', 'Cantidad'],
            {% for d in data %}
              ["{{ d.0 }}", {{d.1}}],
            {% endfor %}
            ]);


        var options = {
            pieHole: 0.4,
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        
        // Wait for the chart to finish drawing before calling the getImageURI() method.
        google.visualization.events.addListener(chart, 'ready', function () {
          
        document.getElementById('imagen').outerHTML = '<a href="' + chart.getImageURI() + '" target="_blank">Imagen de Grafico</a>';
        });

        chart.draw(data, options);
      }
    </script>

{% endblock %}

{% block contenido_panel %}

<div style="margin:0 1% 10px 1%;border-radius: 6px;background:#f2f2f2;overflow:hidden;padding:10px">  
        <!--<h4 style="color:#c33833;font-weight:bold">Busqueda</h4>-->
        <form method="POST" action="{% url 'informes:graficos' %}">
          {% csrf_token %}
      <div class="form-inline">
        <div class="form-group">
          {% include 'informes/informesList.html'%}
        </div>
                
        <div class="form-group" style="float:right;margin-right:15px">
          <input type="submit" class="btn btn-success" value="Ir">  
        </div>
      </div>
      </form>
    </div>

  <div class="row" style="width:80%;margin:8px auto;">
      <div class="col-8">
          <h2 class="titulos">Egresados que manejan una segunda lengua</h2>
{% if data|length > 0 %}
              <div>
                <a href="{% url 'informes:diecisieteGrafico' %}" class="btn btn-default"><i class="fa fa-file-pdf-o"></i> Generar PDF </a>
              </div>
              <div id="chart_div" style="width: 900px; height: 500px;"></div>
              <div id='imagen'></div>
              <br>
              <table class="table table-hover">
              <thead><tr><th>Opcion</th><th>#Cantidad</th></tr>
              </thead>
            <tbody>
              {% for d in data  %}
                
                <tr> <td>{{ d.0 }}</td><td>{{ d.1 }}</td></tr>
                
              {% endfor %}
            </tbody>
          </table>
          {% else %}
              <span>No hay datos para realizar el grafico</span>
            {% endif %}
      </div>
  </div>
{% endblock %}

oveu/templates/informes/header.html
<html><head><script>
function subst() {
  var vars={};
  var x=window.location.search.substring(1).split('&');
  for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
  var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
  for (var i in x) {
    var y = document.getElementsByClassName(x[i]);
    for (var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
  }
}
</script></head><body style="border:0; margin: 0;" onload="subst()">


<img src="http://127.0.0.1:8000/static/img/img-membrete.jpg" alt="" style=" width:200px;display:block;margin:0 auto;">

</body></html>